### ISSUE TITLE
how to use @sortEnd

### ISSUE THREAD

**Issue by tranquangchau** [Jexordexan/vue-slicksort#25]
Please for me example use @sortEnd, thanks.

**Comment by Jexordexan** [comment]
You should be able to use it like a normal $emitted event
`<SortableList @sortEnd="onSortEnd($event)" ... ></SortableList>

**Comment by atilkan** [comment]
try @sort-end

**Comment by shiny** [comment]
https://jsfiddle.net/1puv2L6c/139/  any advise?

**Comment by TahaBoulehmi** [comment]
@shiny the problem is that the Event "sortend" is emitted in component <SortableList> but the handler is registered for "sortEnd". Note that HTML attributes are case-insensitive and you cannot use v-on to listen to camelCase events when using in-DOM templates. You should probably use "sort-end" instead of "sortEnd".

HTML attribute names are case-insensitive, so browsers will interpret any uppercase characters as lowercase. That means when you’re using in-DOM templates, camelCased names need to use their kebab-cased (hyphen-delimited) equivalents
**You can use Webpack to solve the problem. https://webpack.js.org/
Or change your "sortEnd" event to "input" if it is possible in your case... The only difference is that @input event is fired after sorting has ended with the newly sorted list.**

**Comment by atilkan** [comment]
@Jexordexan Can you close the issue?
