### ISSUE TITLE
Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by ericmcpheron** [Jexordexan/vue-slicksort#59]
I'm randomly getting this error after updating to version 1.1.1.

```
VM121882 vue-slicksort.umd.js:713
Uncaught TypeError: Cannot read property 'x' of undefined
    at VueComponent.transitionHelperIntoPlace (VM121882 vue-slicksort.umd.js:713)
    at VueComponent.boundFn [as transitionHelperIntoPlace] (VM121357 vue.esm.js:191)
    at VueComponent.handleSortEnd (VM121882 vue-slicksort.umd.js:691)
    at boundFn (VM121357 vue.esm.js:191)
```

It's failing here in the _transitionHelperIntoPlace_ function.
```
      var targetX = -deltaScroll.left;
 >>>> if (this.translate.x > 0) {
        // Diff against right edge when moving to the right
        targetX += newIndexNode.offsetLeft + newIndexNode.offsetWidth - (indexNode.offsetLeft + indexNode.offsetWidth);
      } else {
        targetX += newIndexNode.offsetLeft - indexNode.offsetLeft;
      }
```

**Comment by Jexordexan** [comment]
@andens can you take a look at this? Might just need a null check somewhere

**Comment by ericmcpheron** [comment]
I created a pull request which I think fixes the issue. #61

**Comment by wukaMM** [comment]
Hi, 
I have installed the latest version, and the error "Cannot read property 'x' of undefined" is gone. But when I single or double click a item, it still maybe suspended sometimes, then I can only refresh the page.
Is there any suggestions? Thank you for your help.

**Comment by andens** [comment]
@wukaMM I couldn't reproduce such behavior. Can you pinpoint when it happens?

**Comment by preterer** [comment]
@andens 
Using latest version of the plugin:

1. Create component that mixes `ContainerMixin` 
2. Create component that mixes `ElementMixin` and uses `HandleDirective`
3. Insert a few elements into your list
4a. After page refresh just click on your handle and you get the original error (`Cannot read property 'x' of undefined`)
4b. Move elements from bottom to top, and after a few times it will stop working for me.

Extra info:
  - I'm using the @drag-end handler
  - I'm using 2 lists on a single page
  - 4a happens on both lists
  - 4b only happens on the 2nd list, which uses the @drag-end
  - I use `div` elements instead of `ul` and `li`

Issue 4a is still about lines 406 and 415 of `ContainerMixin`. Since there is no error thrown when issue 4b happends, I cannot tell you anymore about it.

**Comment by preterer** [comment]
I've created a pull-request (https://github.com/Jexordexan/vue-slicksort/pull/68), which fixes 4a for me. It seems to fix 4b as well (I have changed my @sort-end, to be more efficient, so it might be that too).
